### PR TITLE
Cleanup and place for extended examples and articles related "stuff"

### PR DESCRIPTION
**Pull request by mdzik**
@llaniewski - please accept new subfolder ;)

Examples_And_Papers/wip_SomeIdentifcation
postpublication
Examples_And_Papers/Authors_XXX_Date + Readme with DOI, PDF? etc.

If this catches up, maybe  - separate repo?

### CODE REVIEW

**Review by llaniewski — CHANGES_REQUESTED** [review]
Looks great, but I would appreciate if we would start adding per-folder README.md files, which describes what's what. Similar to https://github.com/CFD-GO/TCLB/tree/develop/example/article/ThermocapillaryFlow

As for separate repo, I think that it will come to that, as we will want to publish more and more reproducible cases (Me, You, Travis). But we have to workout good practices for that.

@mdzik I'll merge when you add README.md to the folder.

**Comment by ggruszczynski** [comment]
@mdzik 
Please change `CLBc.addGeomParam('ny', 2)` to `CLBc.addGeomParam('ny', 3)`

Otherwise the GPU version crashes with:
`[ 0] FATAL ERROR: invalid configuration argument in LatticeContainer.inc.cpp at line 748`

**Review by llaniewski — APPROVED** [review]

**Comment by llaniewski** [comment]
@ggruszczynski If everything is ok, accept review and merge.

**Review by ggruszczynski — COMMENTED** [review]
IMHO the scalling is buggy. It does not preserve the Damkohler similarity number.
Let's merge it as initial version and improve is subsequent PR.

**Pull request merged**
